---

    - file: path=/calico state=directory mode=0744

    - name: Get Calico Mesos Executable
      get_url: url=https://github.com/projectcalico/calico-mesos/releases/download/v0.1.5/calico_mesos dest=/calico

    - shell: chmod +x /calico/calico_mesos

    - name: Get Calico Mesos plugin
      get_url: url=https://raw.githubusercontent.com/projectcalico/calico-containers/master/docs/mesos/vagrant-centos/sources/modules.json dest=/etc/mesos-slave/modules

    - name: Get Calicoctl
      get_url: url=https://github.com/projectcalico/calico-containers/releases/download/v0.18.0/calicoctl dest=/opt

    - shell: chmod +x /opt/calicoctl

    - name: Set calicoctl systemd script
      template: src=../templates/calicoctl.service.j2 dest=/usr/lib/systemd/system

