---

    - include: weave.yml

    - name: Systemd script
      template: src=../templates/weave.agent.service.j2 dest=/usr/lib/systemd/system/weave.service

    - service : name=weave state=started enabled=yes

    - wait_for: path=/var/run/weave/weave.sock delay=10

    - wait_for: path=/proc/sys/net/ipv4/conf/weave delay=10
