---
- hosts: tag_Name_Mesos_Master
  connection: local
  gather_facts: True

  tasks:

#  - name: Mesos security Group
#    ec2_group:
#      name: Mesos-SG
#      description: Security Group for Mesos Master
#      vpc_id: vpc-bd98c9d8
#      region: eu-west-1
#          




  - name: Provision a set of instances for Mesos-Marathon Masters
    ec2:
      region: "eu-west-1"
      state: "absent"
      with_items:
       - {{ host }}

#
# - name: Provision a set of instances for Mesos Slaves
#    ec2:
#      key_name: cristian
#      instance_type: t2.micro
#      image: "ami-8b8c57f8"
#      group: "Mesos-SG"
#      wait: true
#      region: "eu-west-1"
#      exact_count: 1
#      count_tag:
#         Name: Mesos-Slave
#      instance_tags:
#         Name: Mesos-Slave
#      user_data: |
#         #!/bin/bash 
#         echo "Defaults:ec2-user !requiretty" > /etc/sudoers.d/disable_requiretty
#    register: slaves
#
#  - name: Add all instance public IPs to host group
#    add_host: hostname={{ item.public_ip }} groupname=slaves
#    with_items: slaves.instances
