---
- hosts: all
  sudo: yes
  remote_user: ec2-user
  gather_facts: True

  vars_files:
    - vars/vars.yml


  tasks:

    - include: tasks/rpms.yml

    - include: tasks/zookeeper.yml
 
    - include: tasks/marathon.yml

    - include: tasks/mesos.yml

    - include: tasks/docker.yml

    - include: tasks/weave-master.yml
      when: weave_enabled == "True"

    - include: tasks/consul-master.yml
      when: consul_enabled == "True"
      tags:
        - consul

    - service : name=mesos-master state=started enabled=yes
   
    - service : name=mesos-slave state=stopped enabled=no

    - name: Recap
      debug: var=hostvars[inventory_hostname]

    - name: Instructions Mesos
      debug: msg="Login into Mesos Console http://{{ ec2_dns_name }}:5050"

    - name: Instructions Marathon
      debug: msg="Login into Marathon Console http://{{ ec2_dns_name }}:8080"
  
  handlers:
    - name: "DockerRestart"
      service : name=docker state=restarted enabled=yes
