---
- hosts: all
  sudo: yes
  remote_user: ec2-user
  gather_facts: True

  vars_files:
    - playbooks/vars/vars.yml


  tasks:

    - include: playbooks/tasks/rpms.yml

    - include: playbooks/tasks/java.yml

    - include: playbooks/tasks/zookeeper-amazon.yml
      when: ansible_distribution  == "Amazon"

    - include: playbooks/tasks/zookeeper-redhat.yml
      when: ansible_distribution == "RedHat"
