---

    - include: consul.yml

    - template: src=../templates/consul.bootstrap.config.json.j2 dest=/etc/consul.d/bootstrap/consul.bootstrap.config.json

    - template: src=../templates/consul.service.master.j2 dest=/usr/lib/systemd/system/consul.service

    - name: Setup optional Consul UI
      get_url: url=https://releases.hashicorp.com/consul/0.6.3/consul_0.6.3_web_ui.zip dest=/home/ec2-user
      when: consul_UI == "true"

    - name: Uncompress options Consul UI
      unarchive: src=/home/ec2-user/consul_0.6.3_web_ui.zip copy=no
      when: consul_UI == "true"

    - name: Start UI
      command: consul agent -ui
      when: consul_UI == "true"

    - service: name="consul" state=started enabled=yes

