---

    - name: Install Unzip
      yum: pkg={{item}} state=latest update_cache=yes
      with_items:
      - unzip


    - name: Get Consul executable
      get_url: url=https://releases.hashicorp.com/consul/0.6.3/consul_0.6.3_linux_amd64.zip dest=/tmp

    - unarchive: src=/tmp/consul_0.6.3_linux_amd64.zip dest=/usr/local/bin copy=no

    - file: path=/usr/local/bin/consul owner=ec2-user mode=0744

    - file: path=/var/consul state=directory mode=0744

    - file: path=/etc/consul.d state=directory mode=0744

    - file: path=/etc/consul.d/{{ item }} owner=ec2-user mode=0744 state=directory
      with_items:
        - bootstrap
        - server
        - client
