---

    - name: Install Marathon 
      yum: pkg={{item}} state=latest update_cache=yes
      with_items:
      - marathon

    - file: path=/etc/marathon/conf state=directory mode=0744
    - template : src="../templates/external_ip.j2" dest="/etc/marathon/conf/hostname"

    - service : name=marathon state=started enabled=yes
