---

    - include: docker.yml

    - stat: path=/usr/local/bin/weave
      register: weave_executable

    - name: Get Weave executable
      get_url: url=http://git.io/weave dest=/usr/local/bin/weave
      when: weave_executable.stat.exists == False

    - file: path=/usr/local/bin/weave owner=ec2-user mode=0744
