---

    - include: weave.yml

    - name: Systemd script.
      template: src=../templates/weave.service.j2 dest=/usr/lib/systemd/system/weave.service

    - service : name=weave state=started enabled=yes

    - wait_for: path=/var/run/weave/weave.sock delay=10

    - wait_for: path=/proc/sys/net/ipv4/conf/weave delay=10

    - name: Create file for Integration Mesos/Weave
      command: touch /etc/mesos-slave/docker_socket
      args:
       creates: /etc/mesos-slave/docker_socket
    - lineinfile: dest=/etc/mesos-slave/docker_socket state=present line="/var/run/weave/weave.sock"
      register: RestartMesosSlave

    - service: name=mesos-slave state=restarted enabled=true
      when: RestartMesosSlave.changed

