---
- hosts: localhost
  connection: local
  gather_facts: False

  tasks:

  - name: Mesos security Group
    ec2_group:
      name: Mesos-SG
      description: Security Group for Mesos Master
      vpc_id: vpc-bd98c9d8
      region: eu-west-1
      rules:
        - proto: tcp
          from_port: 22
          to_port: 22
          cidr_ip: 0.0.0.0/0
        - proto: icmp
          from_port: 8 # icmp type, -1 = any type
          to_port:  -1 # icmp subtype, -1 = any subtype
          cidr_ip: 0.0.0.0/0
        - proto: tcp
          from_port: 5050 
          to_port: 5050
          cidr_ip: 0.0.0.0/0
        - proto: tcp
          from_port: 8080
          to_port: 8080
          cidr_ip: 0.0.0.0/0
        - proto: tcp 
          from_port: 2181
          to_port: 2181
          cidr_ip: 0.0.0.0/0 




  - name: Provision a set of instances for Mesos-Marathon Masters
    ec2:
      key_name: cristian
      instance_type: t2.micro
      image: "ami-8b8c57f8"
      group: "Mesos-SG"
      wait: true
      region: "eu-west-1"
      exact_count: 1
      count_tag:
         Name: Demo-Mesos
      instance_tags:
         Name: Demo-Mesos
    register: master 

  - name: Add all instance public IPs to host group
    add_host: hostname={{ item.public_ip }} groupname=masters
    with_items: master.instances

  - name: Provision a set of instances for Mesos Slaves
    ec2:
      key_name: cristian
      instance_type: t2.micro
      image: "ami-8b8c57f8"
      group: "Mesos-SG"
      wait: true
      region: "eu-west-1"
      exact_count: 1
      count_tag:
         Name: Mesos-Slave
      instance_tags:
         Name: Mesos-Slave
    register: slaves

  - name: Add all instance public IPs to host group
    add_host: hostname={{ item.public_ip }} groupname=slaves
    with_items: slaves.instances
