---
- hosts: localhost
  connection: local
  gather_facts: False

  tasks:

  - name: example ec2 group
    ec2_group:
      name: Mesos-SG
      description: Security Group for Mesos Master
      vpc_id: vpc-bd98c9d8
      region: eu-west-1
      rules:
        - proto: tcp
          from_port: 22
          to_port: 22
          cidr_ip: 0.0.0.0/0
        - proto: icmp
          from_port: 8 # icmp type, -1 = any type
          to_port:  -1 # icmp subtype, -1 = any subtype
          cidr_ip: 0.0.0.0/0
        - proto: tcp
          from_port: 5050 
          to_port: 5050
          cidr_ip: 0.0.0.0/0
        - proto: tcp
          from_port: 8080
          to_port: 8080
          cidr_ip: 0.0.0.0/0




  - name: Provision a set of instances
    ec2:
      key_name: cristian
      instance_type: t2.micro
      image: "ami-8b8c57f8"
      group: "Mesos-SG"
      wait: true
      region: "eu-west-1"
      exact_count: 1
      count_tag:
         Name: Demo-Mesos
      instance_tags:
         Name: Demo-Mesos
    register: ec2

  - name: Add all instance public IPs to host group
    add_host: hostname={{ item.public_ip }} groupname=masters
    with_items: ec2.instances
