---
- hosts: "tag_Name_Mesos_Master-{{ ansible_user_id }}-{{ flavour }}"
  sudo: yes
  remote_user: ec2-user
  gather_facts: True

  tasks:

    - include: tasks/rpms.yml

    - include: tasks/zookeeper.yml
 
    - include: tasks/marathon.yml

    - include: tasks/mesos.yml

    - service : name=mesos-master state=started enabled=yes

    - name: Recap
      debug: var=hostvars[inventory_hostname]

    - name: Instructions Mesos
      debug: msg="Login into Mesos Console http://{{ ec2_dns_name }}:5050"

    - name: Instructions Marathon
      debug: msg="Login into Marathon Console http://{{ ec2_dns_name }}:8080"
