---
- hosts: tag_Name_Demo_Mesos
  sudo: yes
  remote_user: ec2-user
  gather_facts: True

  tasks:

    - copy: src="rpms/cloudera-cdh-4-0.x86_64.rpm" dest=/tmp/
    - copy: src="rpms/mesosphere-el-repo-7-1.noarch.rpm" dest="/tmp"

    - name: Check if Mesosphere EPEL Repo is installed
      command: rpm -q mesosphere-el-repo-7-1
      register: rpm_check_mesos_repo
      failed_when: false
      changed_when: false

    - name: Execute script if mesosphere is not installed
      command: rpm -Uvh /tmp/mesosphere-el-repo-7-1.noarch.rpm 
      when: rpm_check_mesos_repo.stdout.find('is not installed') != -1

    - name: Check if zookeeper EPEL Repo is installed
      command: rpm -q cloudera-cdh-4-0
      register: rpm_check_zookeeper_repo
      failed_when: false
      changed_when: false

    - name: Execute script if mesosphere is not installed
      command: rpm -Uvh /tmp/cloudera-cdh-4-0.x86_64.rpm
      when: rpm_check_zookeeper_repo.stdout.find('is not installed') != -1



    - name: Install different software packages
      yum: pkg={{item}} state=latest update_cache=yes
      with_items:
      - mesos
      - marathon
      - zookeeper

    - name: Systemd script.
      template: src=templates/zookeeper.service.j2 dest=/usr/lib/systemd/system/zookeeper.service

    - name: zoo.cfg
      template: src=templates/zookeeper.cfg.j2 dest=/etc/zookeeper/conf/zoo.cfg

    - service : name=zookeeper state=started enabled=yes
    - service : name=mesos-master state=started enabled=yes
    - service : name=marathon state=started enabled=yes

    - name: Recap
      debug: var=hostvars[inventory_hostname]

    - name: Instructions Mesos
      debug: msg="Login into Mesos Console http://{{ ec2_dns_name }}:5050"

    - name: Instructions Marathon
      debug: msg="Login into Marathon Console http://{{ ec2_dns_name }}:8080"
